### ISSUE TITLE
TODO: CREATE ALL EVENTS PAGE

### ISSUE THREAD

**Issue by PaulBratslavsky** [PaulBratslavsky/nextjs-build-in-public#19]
Creating the events page. 
- this is where I want to show all the events.  It will be based on the same event card you made, except I want to have it show the image of the user who created the event.

Here is what the UI can look like.  Fell free to have any creative freedom.  This is just a reference.
<img width="1289" alt="2023-10-28_00-10-54" src="https://github.com/PaulBratslavsky/nextjs-build-in-public/assets/6153188/47ea92e5-fa2c-461f-8725-fc9572cb3599">

Let me know if there are any questions.

**Comment by ztxone** [comment]
Actually i like a bit different design for all events, cuz all referenced templates have only several versions of design around 1 event... to my mind it's not the way to display list of all events in the app. So i plan to rework a bit this version of a page:

<img width="646" alt="Screenshot 2023-10-28 at 23 04 55" src="https://github.com/PaulBratslavsky/nextjs-build-in-public/assets/39146381/2f45be0e-d8d6-4809-9245-412d682e10d9">

But instead of "day one" separate list of event to monthes: 

**this month**

_list of events cards_

**next month (november 2023)**

_list of events_

...etc 

And then will be ability to switch between different visual styles of event cards - tiles and list

What do you think @PaulBratslavsky ?

**Comment by ztxone** [comment]
Built my view on Events page. Check PR, please)

**Comment by PaulBratslavsky** [comment]
@ztxone thank you looks good.  I am going to think about what is next in terms of ui.  I  made some small changes in the dashboard view ui.  

There is some work on Stapi side of things that I will work Friday and the weekend.  In terms of UI I am open for suggestion.  Maybe we can style the add-project form better, and same for the profile form.

I am thinking of just get the app s complete as possible ( working order in terms of basic features ) than if we need to we can keep improving the UI and refactor where necessary.  

I am going to merge the PR.

Thanks again for all your awesome help.
